name: Maven CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '35 4 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: 'java'

    - name: Build with Maven
      run: ./mvnw -B verify 

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:java"

    - name: Run (test) program with default values
      run: java -jar ./target/100-prisoners-1.0.jar

    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v3
